//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemVenda
    {
        public int idOrdemVenda { get; set; }
        public int? Material { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Valor { get; set; }
        public string quantidade { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual PrecoVenda PrecoVenda { get; set; }
    }
}
