//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoCompra
    {
        public int idPedCompra { get; set; }
        public Nullable<int> Material { get; set; }
        public Nullable<int> Fornecedor { get; set; }
        public string Quantidade { get; set; }
        public Nullable<int> Valor { get; set; }
    
        public virtual Fornecedor Fornecedor1 { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual PrecoCompra PrecoCompra { get; set; }
    }
}
