//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecoCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrecoCompra()
        {
            this.PedidoCompra = new HashSet<PedidoCompra>();
        }
    
        public int IdPrecoCompra { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoCompra> PedidoCompra { get; set; }
    }
}
