//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecoVenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrecoVenda()
        {
            this.OrdemVenda = new HashSet<OrdemVenda>();
        }
    
        public int idPrecoVenda { get; set; }
        public Nullable<int> Material { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        public virtual Material Material1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemVenda> OrdemVenda { get; set; }
    }
}
